### ISSUE TITLE
I can't sign in with twitter

### ISSUE THREAD

**Issue by gledos** [pastpages/savemy.news#18]

**Comment by palewire** [comment]
Thanks for the heads up. Looks like this was [an issue on Twitter's end](https://github.com/python-social-auth/social-app-django/issues/164). I think I've solved it. Can you sign in now?

**Comment by gledos** [comment]
@palewire 
thx, but i can't sign twitter

`https://www.savemy.news/login/twitter/?next=/`
this is `sign in with twitter` URL, it's back `Server Error (500)`

i use yandex browser and dnscrypt

**Comment by palewire** [comment]
When was the last time you tried?

**Comment by gledos** [comment]
@palewire 
thx, it's work now.

**Comment by palewire** [comment]
Glad to hear it. Thanks again for notifying me.
