### ISSUE TITLE
Add docs and a license

### ISSUE THREAD

**Issue by machawk1** [pastpages/savemy.news#2]
I saw mention of this package via Twitter and came to visit the repo to find very minimal documentation. Before other users can contribute, it would be useful to first outline how to use the software and basic installation instructions.

Also, please add a LICENSE so contributors know their contributions won't be submitted in vain.

Thanks for putting this together. I hope to explore the software more.

**Comment by palewire** [comment]
LICENSE is in.

**Comment by palewire** [comment]
The [README](https://github.com/pastpages/savemy.news/blob/master/README.md) is updated with installation and configuration instructions.
