### ISSUE TITLE
Missing wsgi requirement when following README instructions

### ISSUE THREAD

**Issue by machawk1** [pastpages/savemy.news#3]
Using a virtualenv, I followed the steps in the README.

Upon running `python manage.py runserver`, I am told, "No module named wsgi":
<details>

> (0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
> November 11, 2017 - 16:43:20
> Django version 1.11.7, using settings 'project.settings'
> Starting development server at http://127.0.0.1:8000/
> Quit the server with CONTROL-C.
> Unhandled exception in thread started by <function wrapper at 0x1063c41b8>
> Traceback (most recent call last):
>   File "/private/tmp/savemy.news/myve/lib/python2.7/site-packages/django/utils/autoreload.py", line 228, in wrapper
>     fn(*args, **kwargs)
>   File "/private/tmp/savemy.news/myve/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 147, in inner_run
>     handler = self.get_handler(*args, **options)
>   File "/private/tmp/savemy.news/myve/lib/python2.7/site-packages/django/contrib/staticfiles/management/commands/runserver.py", line 28, in get_handler
>     handler = super(Command, self).get_handler(*args, **options)
>   File "/private/tmp/savemy.news/myve/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 68, in get_handler
>     return get_internal_wsgi_application()
>   File "/private/tmp/savemy.news/myve/lib/python2.7/site-packages/django/core/servers/basehttp.py", line 57, in get_internal_wsgi_application
>     sys.exc_info()[2])
>   File "/private/tmp/savemy.news/myve/lib/python2.7/site-packages/django/core/servers/basehttp.py", line 47, in get_internal_wsgi_application
>     return import_string(app_path)
>   File "/private/tmp/savemy.news/myve/lib/python2.7/site-packages/django/utils/module_loading.py", line 20, in import_string
>     module = import_module(module_path)
>   File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
>     __import__(name)
> django.core.exceptions.ImproperlyConfigured: WSGI application 'project.wsgi.application' could not be loaded; Error importing module: 'No module named wsgi'

</details>

`pip install wsgi` while still in the virtualenv does not install any further package to meet the requirement.

`pip freeze` returns the following list of installed modules:
<details>

> certifi==2017.7.27.1
> chardet==3.0.4
> click==6.7
> dj-database-url==0.4.2
> Django==1.11.7
> gunicorn==19.7.1
> idna==2.6
> oauthlib==2.0.6
> psycopg2==2.7.3.2
> PyJWT==1.5.3
> python-openid==2.2.5
> pytz==2017.3
> requests==2.18.4
> requests-oauthlib==0.8.0
> savepagenow==0.0.8
> six==1.11.0
> social-auth-app-django==2.0.0
> social-auth-core==1.5.0
> urllib3==1.22
> whitenoise==3.3.1

</details>
 
Python 2.7.13, macOS 10.12.6, commit d2a12fec99830768e4bd0811582b1782163188b4

**Comment by palewire** [comment]
Well that's no good! I'm about to get on a plane but will take a look.
Thanks for trying it out.

**Comment by palewire** [comment]
I suspect (but am not certain) this was an issue in how I configured the Django settings. I never got the error myself, which is weird, but I've pushed a fix to the master branch that I hope will help you. Try pulling from that and let me know if anything changes.

**Comment by machawk1** [comment]
I re-pulled and ran through the README again and can no longer replicate this issue.

**Comment by palewire** [comment]
Hey, I fixed something for once!
