### ISSUE TITLE
SECRET_KEY committed in repo

### ISSUE THREAD

**Issue by rdmurphy** [pastpages/savemy.news#4]
[I think this is bad](https://github.com/pastpages/savemy.news/blob/master/project/settings.py#L23).

[Django docs on `SECRET_KEY`](https://docs.djangoproject.com/en/1.11/ref/settings/#std:setting-SECRET_KEY).

**Comment by palewire** [comment]
Good point. I'll generate a new one and have production pull it from secret Heroku variable. Stand by.

**Comment by palewire** [comment]
I think I've fixed this and pushed the solution.
